# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/free/Documents/clion/bin/cmake/bin/cmake

# The command to remove a file.
RM = /home/free/Documents/clion/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/free/dev/Runecraft/Game

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/free/dev/Runecraft/Game

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/home/free/Documents/clion/bin/cmake/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/home/free/Documents/clion/bin/cmake/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/home/free/Documents/clion/bin/cmake/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/home/free/Documents/clion/bin/cmake/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/free/Documents/clion/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/free/Documents/clion/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/home/free/Documents/clion/bin/cmake/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/home/free/Documents/clion/bin/cmake/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/free/dev/Runecraft/Game/CMakeFiles /home/free/dev/Runecraft/Game/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/free/dev/Runecraft/Game/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Tests

# Build rule for target.
Tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Tests
.PHONY : Tests

# fast build rule for target.
Tests/fast:
	$(MAKE) -f CMakeFiles/Tests.dir/build.make CMakeFiles/Tests.dir/build
.PHONY : Tests/fast

#=============================================================================
# Target rules for targets named Training

# Build rule for target.
Training: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Training
.PHONY : Training

# fast build rule for target.
Training/fast:
	$(MAKE) -f CMakeFiles/Training.dir/build.make CMakeFiles/Training.dir/build
.PHONY : Training/fast

#=============================================================================
# Target rules for targets named Game

# Build rule for target.
Game: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Game
.PHONY : Game

# fast build rule for target.
Game/fast:
	$(MAKE) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/build
.PHONY : Game/fast

EasyBMP_1.06/EasyBMP.o: EasyBMP_1.06/EasyBMP.cpp.o

.PHONY : EasyBMP_1.06/EasyBMP.o

# target to build an object file
EasyBMP_1.06/EasyBMP.cpp.o:
	$(MAKE) -f CMakeFiles/Tests.dir/build.make CMakeFiles/Tests.dir/EasyBMP_1.06/EasyBMP.cpp.o
	$(MAKE) -f CMakeFiles/Training.dir/build.make CMakeFiles/Training.dir/EasyBMP_1.06/EasyBMP.cpp.o
	$(MAKE) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/EasyBMP_1.06/EasyBMP.cpp.o
.PHONY : EasyBMP_1.06/EasyBMP.cpp.o

EasyBMP_1.06/EasyBMP.i: EasyBMP_1.06/EasyBMP.cpp.i

.PHONY : EasyBMP_1.06/EasyBMP.i

# target to preprocess a source file
EasyBMP_1.06/EasyBMP.cpp.i:
	$(MAKE) -f CMakeFiles/Tests.dir/build.make CMakeFiles/Tests.dir/EasyBMP_1.06/EasyBMP.cpp.i
	$(MAKE) -f CMakeFiles/Training.dir/build.make CMakeFiles/Training.dir/EasyBMP_1.06/EasyBMP.cpp.i
	$(MAKE) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/EasyBMP_1.06/EasyBMP.cpp.i
.PHONY : EasyBMP_1.06/EasyBMP.cpp.i

EasyBMP_1.06/EasyBMP.s: EasyBMP_1.06/EasyBMP.cpp.s

.PHONY : EasyBMP_1.06/EasyBMP.s

# target to generate assembly for a file
EasyBMP_1.06/EasyBMP.cpp.s:
	$(MAKE) -f CMakeFiles/Tests.dir/build.make CMakeFiles/Tests.dir/EasyBMP_1.06/EasyBMP.cpp.s
	$(MAKE) -f CMakeFiles/Training.dir/build.make CMakeFiles/Training.dir/EasyBMP_1.06/EasyBMP.cpp.s
	$(MAKE) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/EasyBMP_1.06/EasyBMP.cpp.s
.PHONY : EasyBMP_1.06/EasyBMP.cpp.s

GameSource/Runecraft.o: GameSource/Runecraft.cpp.o

.PHONY : GameSource/Runecraft.o

# target to build an object file
GameSource/Runecraft.cpp.o:
	$(MAKE) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/GameSource/Runecraft.cpp.o
.PHONY : GameSource/Runecraft.cpp.o

GameSource/Runecraft.i: GameSource/Runecraft.cpp.i

.PHONY : GameSource/Runecraft.i

# target to preprocess a source file
GameSource/Runecraft.cpp.i:
	$(MAKE) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/GameSource/Runecraft.cpp.i
.PHONY : GameSource/Runecraft.cpp.i

GameSource/Runecraft.s: GameSource/Runecraft.cpp.s

.PHONY : GameSource/Runecraft.s

# target to generate assembly for a file
GameSource/Runecraft.cpp.s:
	$(MAKE) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/GameSource/Runecraft.cpp.s
.PHONY : GameSource/Runecraft.cpp.s

ImageAnalyzer/ImageAnalyzer.o: ImageAnalyzer/ImageAnalyzer.cpp.o

.PHONY : ImageAnalyzer/ImageAnalyzer.o

# target to build an object file
ImageAnalyzer/ImageAnalyzer.cpp.o:
	$(MAKE) -f CMakeFiles/Tests.dir/build.make CMakeFiles/Tests.dir/ImageAnalyzer/ImageAnalyzer.cpp.o
	$(MAKE) -f CMakeFiles/Training.dir/build.make CMakeFiles/Training.dir/ImageAnalyzer/ImageAnalyzer.cpp.o
	$(MAKE) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/ImageAnalyzer/ImageAnalyzer.cpp.o
.PHONY : ImageAnalyzer/ImageAnalyzer.cpp.o

ImageAnalyzer/ImageAnalyzer.i: ImageAnalyzer/ImageAnalyzer.cpp.i

.PHONY : ImageAnalyzer/ImageAnalyzer.i

# target to preprocess a source file
ImageAnalyzer/ImageAnalyzer.cpp.i:
	$(MAKE) -f CMakeFiles/Tests.dir/build.make CMakeFiles/Tests.dir/ImageAnalyzer/ImageAnalyzer.cpp.i
	$(MAKE) -f CMakeFiles/Training.dir/build.make CMakeFiles/Training.dir/ImageAnalyzer/ImageAnalyzer.cpp.i
	$(MAKE) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/ImageAnalyzer/ImageAnalyzer.cpp.i
.PHONY : ImageAnalyzer/ImageAnalyzer.cpp.i

ImageAnalyzer/ImageAnalyzer.s: ImageAnalyzer/ImageAnalyzer.cpp.s

.PHONY : ImageAnalyzer/ImageAnalyzer.s

# target to generate assembly for a file
ImageAnalyzer/ImageAnalyzer.cpp.s:
	$(MAKE) -f CMakeFiles/Tests.dir/build.make CMakeFiles/Tests.dir/ImageAnalyzer/ImageAnalyzer.cpp.s
	$(MAKE) -f CMakeFiles/Training.dir/build.make CMakeFiles/Training.dir/ImageAnalyzer/ImageAnalyzer.cpp.s
	$(MAKE) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/ImageAnalyzer/ImageAnalyzer.cpp.s
.PHONY : ImageAnalyzer/ImageAnalyzer.cpp.s

ImageAnalyzer/LinAlgExtended.o: ImageAnalyzer/LinAlgExtended.cpp.o

.PHONY : ImageAnalyzer/LinAlgExtended.o

# target to build an object file
ImageAnalyzer/LinAlgExtended.cpp.o:
	$(MAKE) -f CMakeFiles/Tests.dir/build.make CMakeFiles/Tests.dir/ImageAnalyzer/LinAlgExtended.cpp.o
	$(MAKE) -f CMakeFiles/Training.dir/build.make CMakeFiles/Training.dir/ImageAnalyzer/LinAlgExtended.cpp.o
	$(MAKE) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/ImageAnalyzer/LinAlgExtended.cpp.o
.PHONY : ImageAnalyzer/LinAlgExtended.cpp.o

ImageAnalyzer/LinAlgExtended.i: ImageAnalyzer/LinAlgExtended.cpp.i

.PHONY : ImageAnalyzer/LinAlgExtended.i

# target to preprocess a source file
ImageAnalyzer/LinAlgExtended.cpp.i:
	$(MAKE) -f CMakeFiles/Tests.dir/build.make CMakeFiles/Tests.dir/ImageAnalyzer/LinAlgExtended.cpp.i
	$(MAKE) -f CMakeFiles/Training.dir/build.make CMakeFiles/Training.dir/ImageAnalyzer/LinAlgExtended.cpp.i
	$(MAKE) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/ImageAnalyzer/LinAlgExtended.cpp.i
.PHONY : ImageAnalyzer/LinAlgExtended.cpp.i

ImageAnalyzer/LinAlgExtended.s: ImageAnalyzer/LinAlgExtended.cpp.s

.PHONY : ImageAnalyzer/LinAlgExtended.s

# target to generate assembly for a file
ImageAnalyzer/LinAlgExtended.cpp.s:
	$(MAKE) -f CMakeFiles/Tests.dir/build.make CMakeFiles/Tests.dir/ImageAnalyzer/LinAlgExtended.cpp.s
	$(MAKE) -f CMakeFiles/Training.dir/build.make CMakeFiles/Training.dir/ImageAnalyzer/LinAlgExtended.cpp.s
	$(MAKE) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/ImageAnalyzer/LinAlgExtended.cpp.s
.PHONY : ImageAnalyzer/LinAlgExtended.cpp.s

ImageAnalyzer/LineDrawer.o: ImageAnalyzer/LineDrawer.cpp.o

.PHONY : ImageAnalyzer/LineDrawer.o

# target to build an object file
ImageAnalyzer/LineDrawer.cpp.o:
	$(MAKE) -f CMakeFiles/Tests.dir/build.make CMakeFiles/Tests.dir/ImageAnalyzer/LineDrawer.cpp.o
	$(MAKE) -f CMakeFiles/Training.dir/build.make CMakeFiles/Training.dir/ImageAnalyzer/LineDrawer.cpp.o
	$(MAKE) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/ImageAnalyzer/LineDrawer.cpp.o
.PHONY : ImageAnalyzer/LineDrawer.cpp.o

ImageAnalyzer/LineDrawer.i: ImageAnalyzer/LineDrawer.cpp.i

.PHONY : ImageAnalyzer/LineDrawer.i

# target to preprocess a source file
ImageAnalyzer/LineDrawer.cpp.i:
	$(MAKE) -f CMakeFiles/Tests.dir/build.make CMakeFiles/Tests.dir/ImageAnalyzer/LineDrawer.cpp.i
	$(MAKE) -f CMakeFiles/Training.dir/build.make CMakeFiles/Training.dir/ImageAnalyzer/LineDrawer.cpp.i
	$(MAKE) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/ImageAnalyzer/LineDrawer.cpp.i
.PHONY : ImageAnalyzer/LineDrawer.cpp.i

ImageAnalyzer/LineDrawer.s: ImageAnalyzer/LineDrawer.cpp.s

.PHONY : ImageAnalyzer/LineDrawer.s

# target to generate assembly for a file
ImageAnalyzer/LineDrawer.cpp.s:
	$(MAKE) -f CMakeFiles/Tests.dir/build.make CMakeFiles/Tests.dir/ImageAnalyzer/LineDrawer.cpp.s
	$(MAKE) -f CMakeFiles/Training.dir/build.make CMakeFiles/Training.dir/ImageAnalyzer/LineDrawer.cpp.s
	$(MAKE) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/ImageAnalyzer/LineDrawer.cpp.s
.PHONY : ImageAnalyzer/LineDrawer.cpp.s

ImageAnalyzer/ShapeDescriptors.o: ImageAnalyzer/ShapeDescriptors.cpp.o

.PHONY : ImageAnalyzer/ShapeDescriptors.o

# target to build an object file
ImageAnalyzer/ShapeDescriptors.cpp.o:
	$(MAKE) -f CMakeFiles/Tests.dir/build.make CMakeFiles/Tests.dir/ImageAnalyzer/ShapeDescriptors.cpp.o
	$(MAKE) -f CMakeFiles/Training.dir/build.make CMakeFiles/Training.dir/ImageAnalyzer/ShapeDescriptors.cpp.o
	$(MAKE) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/ImageAnalyzer/ShapeDescriptors.cpp.o
.PHONY : ImageAnalyzer/ShapeDescriptors.cpp.o

ImageAnalyzer/ShapeDescriptors.i: ImageAnalyzer/ShapeDescriptors.cpp.i

.PHONY : ImageAnalyzer/ShapeDescriptors.i

# target to preprocess a source file
ImageAnalyzer/ShapeDescriptors.cpp.i:
	$(MAKE) -f CMakeFiles/Tests.dir/build.make CMakeFiles/Tests.dir/ImageAnalyzer/ShapeDescriptors.cpp.i
	$(MAKE) -f CMakeFiles/Training.dir/build.make CMakeFiles/Training.dir/ImageAnalyzer/ShapeDescriptors.cpp.i
	$(MAKE) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/ImageAnalyzer/ShapeDescriptors.cpp.i
.PHONY : ImageAnalyzer/ShapeDescriptors.cpp.i

ImageAnalyzer/ShapeDescriptors.s: ImageAnalyzer/ShapeDescriptors.cpp.s

.PHONY : ImageAnalyzer/ShapeDescriptors.s

# target to generate assembly for a file
ImageAnalyzer/ShapeDescriptors.cpp.s:
	$(MAKE) -f CMakeFiles/Tests.dir/build.make CMakeFiles/Tests.dir/ImageAnalyzer/ShapeDescriptors.cpp.s
	$(MAKE) -f CMakeFiles/Training.dir/build.make CMakeFiles/Training.dir/ImageAnalyzer/ShapeDescriptors.cpp.s
	$(MAKE) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/ImageAnalyzer/ShapeDescriptors.cpp.s
.PHONY : ImageAnalyzer/ShapeDescriptors.cpp.s

Tests/test.o: Tests/test.cpp.o

.PHONY : Tests/test.o

# target to build an object file
Tests/test.cpp.o:
	$(MAKE) -f CMakeFiles/Tests.dir/build.make CMakeFiles/Tests.dir/Tests/test.cpp.o
.PHONY : Tests/test.cpp.o

Tests/test.i: Tests/test.cpp.i

.PHONY : Tests/test.i

# target to preprocess a source file
Tests/test.cpp.i:
	$(MAKE) -f CMakeFiles/Tests.dir/build.make CMakeFiles/Tests.dir/Tests/test.cpp.i
.PHONY : Tests/test.cpp.i

Tests/test.s: Tests/test.cpp.s

.PHONY : Tests/test.s

# target to generate assembly for a file
Tests/test.cpp.s:
	$(MAKE) -f CMakeFiles/Tests.dir/build.make CMakeFiles/Tests.dir/Tests/test.cpp.s
.PHONY : Tests/test.cpp.s

Training/Training.o: Training/Training.cpp.o

.PHONY : Training/Training.o

# target to build an object file
Training/Training.cpp.o:
	$(MAKE) -f CMakeFiles/Training.dir/build.make CMakeFiles/Training.dir/Training/Training.cpp.o
.PHONY : Training/Training.cpp.o

Training/Training.i: Training/Training.cpp.i

.PHONY : Training/Training.i

# target to preprocess a source file
Training/Training.cpp.i:
	$(MAKE) -f CMakeFiles/Training.dir/build.make CMakeFiles/Training.dir/Training/Training.cpp.i
.PHONY : Training/Training.cpp.i

Training/Training.s: Training/Training.cpp.s

.PHONY : Training/Training.s

# target to generate assembly for a file
Training/Training.cpp.s:
	$(MAKE) -f CMakeFiles/Training.dir/build.make CMakeFiles/Training.dir/Training/Training.cpp.s
.PHONY : Training/Training.cpp.s

Training/main.o: Training/main.cpp.o

.PHONY : Training/main.o

# target to build an object file
Training/main.cpp.o:
	$(MAKE) -f CMakeFiles/Training.dir/build.make CMakeFiles/Training.dir/Training/main.cpp.o
.PHONY : Training/main.cpp.o

Training/main.i: Training/main.cpp.i

.PHONY : Training/main.i

# target to preprocess a source file
Training/main.cpp.i:
	$(MAKE) -f CMakeFiles/Training.dir/build.make CMakeFiles/Training.dir/Training/main.cpp.i
.PHONY : Training/main.cpp.i

Training/main.s: Training/main.cpp.s

.PHONY : Training/main.s

# target to generate assembly for a file
Training/main.cpp.s:
	$(MAKE) -f CMakeFiles/Training.dir/build.make CMakeFiles/Training.dir/Training/main.cpp.s
.PHONY : Training/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... Tests"
	@echo "... Training"
	@echo "... Game"
	@echo "... EasyBMP_1.06/EasyBMP.o"
	@echo "... EasyBMP_1.06/EasyBMP.i"
	@echo "... EasyBMP_1.06/EasyBMP.s"
	@echo "... GameSource/Runecraft.o"
	@echo "... GameSource/Runecraft.i"
	@echo "... GameSource/Runecraft.s"
	@echo "... ImageAnalyzer/ImageAnalyzer.o"
	@echo "... ImageAnalyzer/ImageAnalyzer.i"
	@echo "... ImageAnalyzer/ImageAnalyzer.s"
	@echo "... ImageAnalyzer/LinAlgExtended.o"
	@echo "... ImageAnalyzer/LinAlgExtended.i"
	@echo "... ImageAnalyzer/LinAlgExtended.s"
	@echo "... ImageAnalyzer/LineDrawer.o"
	@echo "... ImageAnalyzer/LineDrawer.i"
	@echo "... ImageAnalyzer/LineDrawer.s"
	@echo "... ImageAnalyzer/ShapeDescriptors.o"
	@echo "... ImageAnalyzer/ShapeDescriptors.i"
	@echo "... ImageAnalyzer/ShapeDescriptors.s"
	@echo "... Tests/test.o"
	@echo "... Tests/test.i"
	@echo "... Tests/test.s"
	@echo "... Training/Training.o"
	@echo "... Training/Training.i"
	@echo "... Training/Training.s"
	@echo "... Training/main.o"
	@echo "... Training/main.i"
	@echo "... Training/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

